[package]
name = "rust_xlsxwriter"
description = "A Rust library for writing Excel 2007 xlsx files"
authors = ["John McNamara <jmcnamara@cpan.org>"]
homepage = "https://rustxlsxwriter.github.io"
repository = "https://github.com/jmcnamara/rust_xlsxwriter"
keywords = ["excel", "xlsx"]
readme = "README.md"
license = "MIT OR Apache-2.0"
version = "0.32.0"
edition = "2021"

[dependencies]
chrono = {version = "0.4.24", default-features = false, features = ["clock"]}
zip = {version = "0.6.2", default-features = false, features = ["deflate"]}
itertools = "0.10.5"
regex = "1.7.3"
lazy_static = "1.4.0"

[dev-dependencies]
pretty_assertions = "1.3.0"

[features]
default = []

# Config to test double/multiple saves for all test cases.
test_resave = []

# Some local package management and release check commands.
# Uses Cargo Commander.
[package.metadata.commands]
spellcheck = {cmd = [
    "for f in src/*.rs; do aspell --lang=en_US --check $f; done",
    "for f in examples/*.rs; do aspell --lang=en_US --check $f; done",
    "aspell --lang=en_US --check examples/README.md",
    "aspell --lang=en_US --check README.md"
]}

coverage = {cmd = [
    "rm -rf target/coverage",
    "mkdir -p target/coverage",
    "CARGO_INCREMENTAL=0 RUSTFLAGS='-Cinstrument-coverage' LLVM_PROFILE_FILE='target/coverage/rust_xlsxwriter-%p-%m.profraw' cargo test",
    "grcov target/coverage/ --binary-path ./target/debug/deps/ -s src -t lcov --branch -o target/coverage/lcov.info",
    "grcov target/coverage/ --binary-path ./target/debug/deps/ -s src -t html --branch -o target/coverage/html",
    "rm target/coverage/*.profraw",
    "open target/coverage/html/index.html"
]}

release_check = {cmd = ["../release/release_check.sh"]}

# Profile
# cargo instruments -t time --example app_perf_test

# Clippy commands
# cargo clippy --all-targets -- -Dwarnings
# cargo +nightly rustdoc-clippy